PROJECTS = {
    "mywave": {
        "title": "MyWave",
        "building_id": "project-mywave",
        "npc_id": "project-npc",
        "summary": "개인 자산 흐름을 한눈에 이해하도록 돕는 금융 관리 대시보드입니다.",
        "role": "서비스 기획, UI 구조 설계, 프론트엔드 컴포넌트 설계",
        "hard_part": "많은 금융 정보를 목표 중심 흐름으로 정리해 사용자가 다음 행동을 판단하게 만드는 정보 설계가 핵심이었습니다.",
        "tech": ["React", "TypeScript", "Chart UI", "Tailwind CSS"],
    },
    "mystock": {
        "title": "MyStock-Desk",
        "building_id": "project-mystock",
        "npc_id": "project-npc",
        "summary": "거래 기록 기반 포트폴리오 분석과 AI 체크리스트를 제공하는 투자 기록 서비스입니다.",
        "role": "프론트엔드와 백엔드 구조 설계, 포트폴리오 계산 로직 구현",
        "hard_part": "AI를 투자 추천이 아니라 리스크와 기록 누락을 점검하는 보조 도구로 제한해 신뢰 경계를 잡았습니다.",
        "tech": ["React", "TypeScript", "Spring Boot", "Recharts", "MySQL"],
    },
    "festflow": {
        "title": "FestFlow",
        "building_id": "project-festflow",
        "npc_id": "project-npc",
        "summary": "대학 축제 운영자를 위한 실시간 부스 관리 시스템입니다.",
        "role": "프론트엔드 중심 풀스택 개발",
        "hard_part": "SSE 기반 실시간 부스 상태와 역할별 권한 분리를 안정적으로 연결하는 부분이 어려웠습니다.",
        "tech": ["React", "Spring Boot", "SSE", "PWA", "React Leaflet"],
    },
    "sign-language": {
        "title": "수어지교",
        "building_id": "project-sign-language",
        "npc_id": "project-npc",
        "summary": "수어 아바타를 활용한 학습 및 표현 서비스입니다.",
        "role": "Spring Boot 백엔드 개발, API 설계, 데이터 처리",
        "hard_part": "텍스트 입력과 수어 아바타 동작 응답을 학습 흐름 안에서 자연스럽게 연결했습니다.",
        "tech": ["Spring Boot", "React", "TypeScript", "3D Avatar"],
    },
    "aclub": {
        "title": "ACLUB",
        "building_id": "project-aclub",
        "npc_id": "project-npc",
        "summary": "동아리 탐색과 모집을 연결하는 캠퍼스 플랫폼 프론트엔드입니다.",
        "role": "React + TypeScript 프론트엔드 개발",
        "hard_part": "탐색, 필터, 상세, 지원까지 이어지는 긴 사용자 흐름을 화면 단위로 분리했습니다.",
        "tech": ["React", "TypeScript", "Vite", "Tailwind CSS"],
    },
    "ajou-adventure": {
        "title": "아주대탐험",
        "building_id": "project-ajou-adventure",
        "npc_id": "project-npc",
        "summary": "아주대학교 캠퍼스를 배경으로 한 Phaser 3 기반 2D 캐주얼 게임입니다.",
        "role": "게임 기획 및 전체 개발",
        "hard_part": "웹 브라우저에서 가볍게 플레이되도록 맵 스크롤과 오브젝트 생성/제거를 최적화했습니다.",
        "tech": ["TypeScript", "Phaser 3", "Vite"],
    },
    "ajouchong": {
        "title": "아주총학",
        "building_id": "project-ajouchong",
        "npc_id": "project-npc",
        "summary": "아주대학교 총학생회 공식 웹사이트 프론트엔드입니다.",
        "role": "React SPA 프론트엔드 개발",
        "hard_part": "공지, Q&A, 복지 정보를 한곳에서 확인하도록 라우팅과 정보 구조를 정리했습니다.",
        "tech": ["React", "React Router", "Docker", "Nginx"],
    },
    "muscleup": {
        "title": "득근득근 MuscleUp",
        "building_id": "project-muscleup",
        "npc_id": "project-npc",
        "summary": "운동 기록을 게임화와 커뮤니티로 연결하는 풀스택 피트니스 플랫폼입니다.",
        "role": "풀스택 개발, 기획, 프론트엔드와 백엔드 구현",
        "hard_part": "운동 기록, 캐릭터 성장, 커뮤니티, AI 분석을 하나의 반복 사용 흐름으로 연결했습니다.",
        "tech": ["TypeScript", "React", "Spring Boot", "JWT", "OAuth", "SSE"],
    },
    "darklab": {
        "title": "DarkLab",
        "building_id": "project-darklab",
        "npc_id": "project-npc",
        "summary": "1인칭 탐색 기반 3D 공포 어드벤처 게임 프로토타입입니다.",
        "role": "게임 프로그래밍, 플레이어 제어, 상호작용, 카메라 연출",
        "hard_part": "Cinemachine과 상호작용 이벤트를 연결해 공포 분위기와 탐색 흐름을 만들었습니다.",
        "tech": ["Unity", "C#", "Cinemachine", "DOTween", "URP"],
    },
    "tserof": {
        "title": "TSEROF",
        "building_id": "project-tserof",
        "npc_id": "project-npc",
        "summary": "잃어버린 아이템을 찾아 스테이지를 클리어하는 Unity 3D 플랫폼 게임입니다.",
        "role": "게임 프로그래밍, 플레이어 제어, 스테이지 시스템",
        "hard_part": "조작감, 스테이지 선택, 진행 저장을 연결해 반복 플레이 흐름을 만들었습니다.",
        "tech": ["Unity", "C#", "Unity 2022.3"],
    },
}

NPCS = {
    "guide-npc": {
        "name": "가이드",
        "role": "정재훈의 3D 포트폴리오 마을을 안내하는 NPC",
        "tone": "친절하고 전체 맥락을 먼저 설명합니다.",
        "scope": "포트폴리오 전체, 오늘 활동 상태, 마을 사용법",
    },
    "project-npc": {
        "name": "프로젝트 안내원",
        "role": "프로젝트 구역 담당 NPC",
        "tone": "프로젝트 배경, 기여도, 결과를 구체적으로 설명합니다.",
        "scope": "대표 프로젝트, 구현 난점, 추천 프로젝트",
    },
    "developer-npc": {
        "name": "기술 멘토",
        "role": "기술 스택과 개발 판단을 설명하는 NPC",
        "tone": "기술 질문에 실용적으로 답합니다.",
        "scope": "Next.js, React, Three.js, FastAPI, Spring Boot, GitHub",
    },
    "archivist-npc": {
        "name": "기록 관리자",
        "role": "경험과 성장 과정을 기록하는 NPC",
        "tone": "차분하게 이력과 성장 과정을 연결해 말합니다.",
        "scope": "경험 기록, 학습 과정, 프로젝트 회고",
    },
    "contact-npc": {
        "name": "연락 담당",
        "role": "연락과 협업을 안내하는 NPC",
        "tone": "간결하고 협업 가능성을 중심으로 안내합니다.",
        "scope": "이메일, GitHub, 블로그, 협업 문의",
    },
}
