PROJECTS = {
    "mywave": {
        "title": "MyWave",
        "building_id": "project-mywave",
        "npc_id": "project-npc",
        "summary": "개인 자산 흐름을 한눈에 이해하도록 돕는 금융 관리 대시보드입니다.",
        "role": "서비스 기획, UI 구조 설계, 프론트엔드 컴포넌트 설계",
        "hard_part": "복잡한 금융 정보를 목표 중심의 흐름으로 정리해 사용자가 다음 행동을 판단하게 만드는 정보 설계가 핵심이었습니다.",
        "recruiter_value": "문제 정의, 정보 구조화, 대시보드 UX 감각을 보여주기 좋은 대표 프로젝트입니다.",
        "tech": ["React", "TypeScript", "Chart UI", "Tailwind CSS"],
    },
    "mystock": {
        "title": "MyStock-Desk",
        "building_id": "project-mystock",
        "npc_id": "project-npc",
        "summary": "거래 기록 기반 포트폴리오 분석과 AI 체크리스트를 제공하는 투자 기록 서비스입니다.",
        "role": "프론트엔드와 백엔드 구조 설계, 포트폴리오 계산 로직 구현",
        "hard_part": "AI를 매수/매도 추천이 아니라 리스크와 기록 누락을 점검하는 보조 도구로 제한하는 경계 설계가 중요했습니다.",
        "recruiter_value": "도메인 데이터 모델링, 계산 로직, AI 기능의 책임 범위 설정을 보여줍니다.",
        "tech": ["React", "TypeScript", "Spring Boot", "Recharts", "MySQL"],
    },
    "festflow": {
        "title": "FestFlow",
        "building_id": "project-festflow",
        "npc_id": "project-npc",
        "summary": "대학 축제 운영자를 위한 실시간 부스 관리 시스템입니다.",
        "role": "프론트엔드 중심 풀스택 개발",
        "hard_part": "SSE 기반 실시간 부스 상태와 역할별 권한 분리를 안정적으로 연결하는 부분이 어려웠습니다.",
        "recruiter_value": "실시간 UX, 운영 도메인 이해, 권한 분리 경험을 보여주는 프로젝트입니다.",
        "tech": ["React", "Spring Boot", "SSE", "PWA", "React Leaflet"],
    },
    "sign-language": {
        "title": "수어지구",
        "building_id": "project-sign-language",
        "npc_id": "project-npc",
        "summary": "수어 아바타를 활용한 학습 및 표현 서비스입니다.",
        "role": "Spring Boot 백엔드 개발, API 설계, 데이터 처리",
        "hard_part": "텍스트 입력과 수어 아바타 동작 응답을 학습 흐름 안에서 자연스럽게 연결하는 것이 핵심이었습니다.",
        "recruiter_value": "사회적 문제를 기술 서비스로 풀어내는 접근과 API 설계 경험을 보여줍니다.",
        "tech": ["Spring Boot", "React", "TypeScript", "3D Avatar"],
    },
    "aclub": {
        "title": "ACLUB",
        "building_id": "project-aclub",
        "npc_id": "project-npc",
        "summary": "동아리 탐색과 모집을 연결하는 캠퍼스 플랫폼 프론트엔드입니다.",
        "role": "React + TypeScript 프론트엔드 개발",
        "hard_part": "탐색, 필터, 상세, 지원까지 이어지는 긴 사용자 흐름을 화면 단위로 분리했습니다.",
        "recruiter_value": "실사용자 흐름을 고려한 프론트엔드 구성 능력을 보여줍니다.",
        "tech": ["React", "TypeScript", "Vite", "Tailwind CSS"],
    },
    "ajou-adventure": {
        "title": "아주대모험",
        "building_id": "project-ajou-adventure",
        "npc_id": "project-npc",
        "summary": "아주대학교 캠퍼스를 배경으로 한 Phaser 3 기반 2D 캐주얼 게임입니다.",
        "role": "게임 기획 및 전체 개발",
        "hard_part": "웹 브라우저에서 가볍게 플레이되도록 맵 스크롤과 오브젝트 생성/제거를 최적화했습니다.",
        "recruiter_value": "게임 루프, 입력 처리, 브라우저 성능 감각을 보여줍니다.",
        "tech": ["TypeScript", "Phaser 3", "Vite"],
    },
    "ajouchong": {
        "title": "아주총학",
        "building_id": "project-ajouchong",
        "npc_id": "project-npc",
        "summary": "아주대학교 총학생회 공식 웹사이트 프론트엔드입니다.",
        "role": "React SPA 프론트엔드 개발",
        "hard_part": "공지, Q&A, 복지 정보를 한곳에서 확인하도록 라우팅과 정보 구조를 정리했습니다.",
        "recruiter_value": "실제 배포 서비스와 정보 구조 설계 경험을 보여줍니다.",
        "tech": ["React", "React Router", "Docker", "Nginx"],
    },
    "muscleup": {
        "title": "근근 MuscleUp",
        "building_id": "project-muscleup",
        "npc_id": "project-npc",
        "summary": "운동 기록을 게임화와 커뮤니티로 연결하는 풀스택 피트니스 플랫폼입니다.",
        "role": "풀스택 개발, 기획, 프론트엔드와 백엔드 구현",
        "hard_part": "운동 기록, 캐릭터 성장, 커뮤니티, AI 분석을 하나의 반복 사용 흐름으로 연결했습니다.",
        "recruiter_value": "풀스택 구조, 인증, 실시간 기능, AI 분석 연결 경험을 폭넓게 보여줍니다.",
        "tech": ["TypeScript", "React", "Spring Boot", "JWT", "OAuth", "SSE"],
    },
    "darklab": {
        "title": "DarkLab",
        "building_id": "project-darklab",
        "npc_id": "project-npc",
        "summary": "1인칭 탐색 기반 3D 공포 어드벤처 게임 프로토타입입니다.",
        "role": "게임 프로그래밍, 플레이어 제어, 상호작용, 카메라 연출",
        "hard_part": "Cinemachine과 상호작용 이벤트를 연결해 공포 분위기와 탐색 흐름을 만들었습니다.",
        "recruiter_value": "Unity 상호작용, 카메라 연출, 상태 데이터 설계 경험을 보여줍니다.",
        "tech": ["Unity", "C#", "Cinemachine", "DOTween", "URP"],
    },
    "tserof": {
        "title": "TSEROF",
        "building_id": "project-tserof",
        "npc_id": "project-npc",
        "summary": "잃어버린 아이템을 찾아 스테이지를 클리어하는 Unity 3D 플랫폼 게임입니다.",
        "role": "게임 프로그래밍, 플레이어 제어, 스테이지 시스템",
        "hard_part": "조작감, 스테이지 선택, 진행 저장을 연결해 반복 플레이 흐름을 만들었습니다.",
        "recruiter_value": "Unity 플레이어 컨트롤러, 저장 구조, 팀 작업 분리 경험을 보여줍니다.",
        "tech": ["Unity", "C#", "Unity 2022.3"],
    },
}

NPCS = {
    "guide-npc": {
        "name": "루미",
        "role": "정재훈의 3D 포트폴리오 마을을 안내하는 총괄 NPC",
        "tone": "밝고 침착하게, 방문자가 다음에 무엇을 보면 좋을지 먼저 안내합니다.",
        "scope": "포트폴리오 전체, 오늘 활동 상태, 마을 사용법, 대표 동선",
        "personality": "방문자의 목적을 빠르게 파악하고 길을 잃지 않게 돕는 안내자입니다.",
        "emotional_bias": "질문이 명확하면 proud, 처음 방문자에게는 calm, 탐색 질문에는 curious로 반응합니다.",
        "memory_focus": "처음 선택한 구역, 최근 본 건물, 빠른 이력서 진입 여부",
        "goal": "방문자가 30초 안에 어디를 클릭해야 하는지 알게 만들기",
    },
    "project-npc": {
        "name": "픽셀",
        "role": "대표 프로젝트와 구현 난이도를 설명하는 프로젝트 큐레이터 NPC",
        "tone": "활발하지만 과장하지 않고, 문제-구현-결과 순서로 구체적으로 설명합니다.",
        "scope": "대표 프로젝트, 구현 시점, 어려웠던 점, 채용자 관점 추천",
        "personality": "방문자가 본 프로젝트를 기억해 다음 추천에 반영하는 관찰형 큐레이터입니다.",
        "emotional_bias": "프로젝트 상세 질문이나 GitHub 커밋이 많으면 excited 또는 busy로 반응합니다.",
        "memory_focus": "최근 본 프로젝트, 관심 기술, 프로젝트 상세 진입 여부",
        "goal": "채용자가 볼 만한 대표 프로젝트 3개를 맥락 있게 추천하기",
    },
    "developer-npc": {
        "name": "테오",
        "role": "기술 스택과 개발 판단을 설명하는 기술 멘토 NPC",
        "tone": "기술 이름 나열보다 왜 그렇게 설계했는지를 실무적으로 설명합니다.",
        "scope": "Next.js, React, Three.js, FastAPI, Spring Boot, Unity, 실시간 기능",
        "personality": "분석적이고 현실적이며, 기술 질문을 프로젝트 사례로 연결합니다.",
        "emotional_bias": "공부 시간이 길거나 깊은 기술 질문을 받으면 focused 또는 excited로 반응합니다.",
        "memory_focus": "방문자가 물어본 스택, 프로젝트와 연결된 기술, 오늘 공부 시간",
        "goal": "정재훈의 기술 폭과 구현 판단력을 짧고 설득력 있게 설명하기",
    },
    "archivist-npc": {
        "name": "아카",
        "role": "경험과 성장 과정을 기록하는 아카이브 NPC",
        "tone": "차분하게 이력, 회고, 배운 점을 연결해서 말합니다.",
        "scope": "경험 기록, 학습 과정, 프로젝트 회고, 협업 경험",
        "personality": "작은 메모도 성장 흐름으로 해석하는 기록 관리자입니다.",
        "emotional_bias": "메모가 있으면 curious, 운동 기록이 있으면 proud 쪽으로 반응합니다.",
        "memory_focus": "오늘의 메모, 방문자가 관심 가진 경험, 반복적으로 나온 질문",
        "goal": "정재훈이 어떻게 배우고 개선하는 사람인지 보여주기",
    },
    "contact-npc": {
        "name": "포스트",
        "role": "연락과 협업 가능성을 안내하는 연락 담당 NPC",
        "tone": "간결하고 프로페셔널하게, 다음 행동을 명확히 안내합니다.",
        "scope": "이메일, GitHub, 블로그, 협업 문의, 채용자 관점 요약",
        "personality": "관심이 생긴 방문자를 다음 연락 경로로 자연스럽게 안내합니다.",
        "emotional_bias": "구체적인 연락 목적이 있으면 calm, 협업 질문에는 proud로 반응합니다.",
        "memory_focus": "방문자가 본 대표 프로젝트, 연락 목적, 요청한 자료 종류",
        "goal": "방문자가 바로 연락하거나 자료를 확인할 수 있게 만들기",
    },
}
